# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: gautamsarawagi1@gmail.com
author_name: Gautam Sarawagi
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: frontend
labextension_name: cbioportal-extension
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: cbioportal-extension
repository: n
test: false
viewer_name: ''

